run_dir: "path/to/run/dir"
codec_weights: "path/to/codec/weights"
train_data: "/path/to/train/data"
val_data: "path/to/val/data"
# from_checkpoint: "/path/to/denoiser-checkpoint-L.tar"

total_iters: 40000
train_batch: 256
val_batch: 256
num_workers: 16

val_per: 1000 # how often to do validation
samples_per: 1000 # how often to collect output samples
save_ckpts:  [10000, 25000, 40000] 
val_idx: [5, 10, 11, 12, 15, 20, 21, 22] # Samples from the validation set
